twitter:
  consumerapi:
    key: g4J8TDo2YAyHW45PIkc4DtiPK
    secretKey: mvZd9astIhRcJ1fhYRaij8CkCme4Jwc7TlAt7EOOFWkBbNsZtI

  oauthaccess:
    token: 1375191706459602951-fuBlTL6vYE5rR20HQ50SzOo0RiUbJQ
    tokenSecret:  HN0E51mPW5LBrxigBd6lNZcsWIibIS8oSwD43qVCLFYL0

  listenerFlag: echoicmusic

